.PHONY: clean All

All:
	@echo "----------Building project:[ fractal - Debug ]----------"
	@cd "fractal" && "$(MAKE)" -f  "fractal.mk"
clean:
	@echo "----------Cleaning project:[ fractal - Debug ]----------"
	@cd "fractal" && "$(MAKE)" -f  "fractal.mk" clean
